# NFC Configuration for NON-HAL component S3FWRN5
# Samsung Electronics, System LSI Division
# Update Date: 2015/01/05
# Region: All region
# F/W Version dependency: NONE

# Application options
APPL_TRACE_LEVEL=0x05
PROTOCOL_TRACE_LEVEL=0x1FFFFF

# File used for NFA storage
NFA_STORAGE="/data/nfc"

# Maximum Number of Credits allowed by the NFCC
MAX_RF_DATA_CREDITS=1

# Allow UICC to be powered off if there is no traffic
UICC_IDLE_TIMEOUT=60000

# Configure the maximum number of SE (UICC, eSE, DH)
NFA_MAX_EE_SUPPORTED=2

# Configure the single default SE to use
ACTIVE_SE=0x00

# Configure the default routes for ISODEP and off-host AID
DEFAULT_ISODEP_ROUTE=0x00
DEFAULT_OFFHOST_ROUTE=0x00

# Configure the default Destination Gate & PIPE used by HCI
NFA_HCI_DEFAULT_DEST_GATE=4
NFA_HCI_DEFAULT_STATIC_PIPE_ID=0x72
NFA_HCI_SECONDARY_STATIC_PIPE_ID=0x71

# Configure the NFC Extras to use a static pipe
NFA_HCI_STATIC_PIPE_ID_02=0x72
NFA_HCI_STATIC_PIPE_ID_03=0x72

# Force UICC to only listen to technology A and B
UICC_LISTEN_TECH_MASK=0x03

# Force only poll to technology A, B, F, and ISO15693
POLLING_TECH_MASK=0xFF

# Choose the presence-check algorithm for type-4 tag
PRESENCE_CHECK_ALGORITHM=3

# Vendor Specific Proprietary Protocol & Discovery Configuration
NFA_PROPRIETARY_CFG={00:81:82:80:8A:81:90:70:74:F4}

# Specify the desired power state of the controller when the screen is turned off
SCREEN_OFF_POWER_STATE=1
