# NFC Configuration for S3FWRN5
# Update Date: 2014/11/11
# eSE: NFC Standalone
# Region: Other Region
# F/W Version Dependency: NONE

# Default routing information
DEFAULT_ISODEP_ROUTE=0x03
ACTIVE_SE=0x02

# Partial AID setting
PARTIAL_AID={02:01:05}
AID_MATCHING_MODE=0x01

# Tech mask definitions
# Notable bits:
#   NFA_TECHNOLOGY_MASK_A         0x01
#   NFA_TECHNOLOGY_MASK_B         0x02
#   NFA_TECHNOLOGY_MASK_F         0x04
#   NFA_TECHNOLOGY_MASK_ISO15693  0x08
#   NFA_TECHNOLOGY_MASK_B_PRIME   0x10
#   NFA_TECHNOLOGY_MASK_KOVIO     0x20
#   NFA_TECHNOLOGY_MASK_A_ACTIVE  0x40
#   NFA_TECHNOLOGY_MASK_F_ACTIVE  0x80
POLLING_TECH_MASK=0xEF
UICC_LISTEN_TECH_MASK=0x03
P2P_LISTEN_TECH_MASK=0xC4

# Maximum Number of Credits
MAX_RF_DATA_CREDITS=1

# Warm-reset command for Oberthur secure element
OBERTHUR_WARM_RESET_COMMAND=0x03

# Presence Check Method
PRESENCE_CHECK_ALGORITHM=5

# Application options
APPL_TRACE_LEVEL=0xFF
PROTOCOL_TRACE_LEVEL=0xFFFFFFFF
PRESERVE_STORAGE=1
NFA_STORAGE="/data/nfc"

# Power control driver
POWER_CONTROL_DRIVER="/dev/sec-nfc"

# Transport driver
TRANSPORT_DRIVER="/dev/sec-nfc"

# Default poll duration
NFA_DM_DISC_DURATION_POLL=500

# Max transceive length for IsoDep frames
ISO_DEP_MAX_TRANSCEIVE=0xFEFF
